so ~/dotfiles/vim/generalrc
so ~/dotfiles/vim/mappings.vim
if !exists('g:vscode')
    so ~/dotfiles/vim/standardvimrc

let g:ActualTicket = "INTS-4886"
else
    so ~/dotfiles/vim/vscodeNeovimrc
endif

