let g:ActualTicket = "INTS-5329"

so ~/dotfiles/vim/.credencials
so ~/dotfiles/vim/pluginsnew.vim
so ~/dotfiles/vim/nvimLSP.vim
so ~/dotfiles/vim/functions.vim
so ~/dotfiles/vim/github.vim
so ~/dotfiles/vim/snippets.vim

so ~/dotfiles/vim/standardvimrc

so ~/dotfiles/vim/mappings.vim
so ~/dotfiles/vim/colors.vim

